version: '2.4'
services:
  app:
    container_name: app
    mem_limit: 1024m
    mem_reservation: 300m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    build:
      context: ./
    user: '1000:1002'
    ports:
      - 80:80
    volumes:
      - ./:/app:delegated
    environment:
      WEB_DOCUMENT_ROOT: /app/public
    depends_on:
      - redis
  db:
    image: postgres
    restart: always
    environment:
        - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
        - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8081:80
    depends_on:
      - db
      - app
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
volumes:
  mysql:
    driver: local
